# Generated by Django 3.0.4 on 2020-06-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_is_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
