# Generated by Django 3.0.4 on 2020-06-21 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_is_recommended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_recommended',
        ),
    ]
